### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by prendradjaja** [prendradjaja/advent-of-code-2024#1]
- [ ] Solve remaining problems
- [ ] Maybe write missing parsers (i.e. replace hard-coded inputs), i.e. days 4, 6, 7 (Maybe not - I already know how)
- [ ] Re-solve Python days in C (11, 13, 17, 19, 23)
- [ ] Day 5: Try using strtok() to parse comma-separated ints
- [ ] Day 14: Add code for the manual step (spotting the Christmas tree)
